// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prjtlpyvkvqlkexxxkic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByanRscHl2a3ZxbGtleHh4a2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzAxMzAsImV4cCI6MjA2NTYwNjEzMH0.AAiNC98Zp0PF0fpx1oE72zG6wMBSSt-CVp98rAjApUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);